set -e
true
true
/Users/cmdb/Downloads/SPAdes-3.15.5-Darwin/bin/spades-hammer /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/corrected/configs/config.info
/Users/cmdb/miniconda3/bin/python /Users/cmdb/Downloads/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/corrected/corrected.yaml --ext_python_modules_home /Users/cmdb/Downloads/SPAdes-3.15.5-Darwin/share/spades --max_threads 4 --output_dir /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/corrected --gzip_output
true
true
/Users/cmdb/Downloads/SPAdes-3.15.5-Darwin/bin/spades-core /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/configs/config.info
/Users/cmdb/miniconda3/bin/python /Users/cmdb/Downloads/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/scripts/copy_files.py /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/before_rr.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/before_rr.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/assembly_graph_after_simplification.gfa /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/assembly_graph_after_simplification.gfa /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/final_contigs.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/contigs.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/first_pe_contigs.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/first_pe_contigs.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/strain_graph.gfa /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/strain_graph.gfa /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/scaffolds.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/scaffolds.fasta /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/scaffolds.paths /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/scaffolds.paths /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/assembly_graph_with_scaffolds.gfa /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/assembly_graph_with_scaffolds.gfa /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/assembly_graph.fastg /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/assembly_graph.fastg /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/K31/final_contigs.paths /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/contigs.paths
true
/Users/cmdb/miniconda3/bin/python /Users/cmdb/Downloads/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/scaffolds.fasta --misc_dir /Users/cmdb/qbb2022-answers/week1-homework/asm/asm_q2/misc --threshold_for_breaking_scaffolds 3
true
